version: '2'
services:
  redis:
    image: redis:latest
    expose:
      - "6379"

  app:
    build: .
    depends_on:
      - redis
    labels:
      - "SERVICE_8080_NAME=shush"
      - "SERVICE_8080_TAGS=load-balance,urlprefix-shush.*/"
      - "SERVICE_8080_CHECK_TCP=true"
      - "SERVICE_8080_CHECK_INTERVAL=15s"
