version: '2'
services:
  redis:
    image: redis:latest
    expose:
      - "6379"

  app:
    build: .
    depends_on:
      - redis
    labels:
      - "SERVICE_3000_NAME=shush"
      - "SERVICE_3000_TAGS=load-balance"
